# Generated by Django 4.2.8 on 2024-01-14 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choco_type', models.CharField(max_length=4, verbose_name='Choco type')),
                ('nickname', models.CharField(max_length=20, verbose_name='Nickname')),
                ('contents', models.TextField(verbose_name='Contents')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('ip_address', models.GenericIPAddressField(editable=False, null=True)),
                ('box_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.box', verbose_name='Box id')),
            ],
            options={
                'db_table': 'letter',
            },
        ),
    ]
